version: '3.8'

services:
  api-simulator:
    image: dannyshe/api-simulator:latest
    platform: linux/amd64 #pls update base to your local env
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    platform: linux/amd64 #pls update base to your local env
    hostname: local.middleware.com
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=channel_mock
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1111
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    platform: linux/amd64 #pls update base to your local env
    hostname: local.middleware.com
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    driver: bridge