rootArtifactId: CHANNEL-MOCK

spring:
  application:
    name: ${rootArtifactId}
  datasource:
    url: jdbc:mysql://local.middleware.com:3306/channel_mock?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: admin
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      max-lifetime: 10000
  # 添加 JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  redis:
    timeout: 50000ms
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 2
        max-wait: 50000ms
    database: 0
    host: 192.168.1.105
    port: 6379
    
  # 删除 redisson 配置部分
  
  security:
    user:
      name: admin
      password: 123
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    async:
      request-timeout: 10

  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true

logging:
  file:
    path: ${user.home}/logs/${rootArtifactId}
  level:
    com.payment.simulator: INFO


server:
  port: 10051
  tomcat:
    max-threads: 800
    min-spare-threads: 200
    accesslog:
      enabled: true
      rotate: true
      directory: ${logging.path}

management:
  security:
    enabled: true
  endpoints:
    jmx:
      exposure:
        include: info, health, prometheus
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: when_authorized

